//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Merkur.win.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(localdb)\\MSSQLLocalDB;Initial Catalog=PAQUETERIAMK_f173940afcc344bea" +
            "9771f0119ce5f4d;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustS" +
            "erverCertificate=True")]
        public string PAQUETERIAMK_f173940afcc344bea9771f0119ce5f4dConnectionString {
            get {
                return ((string)(this["PAQUETERIAMK_f173940afcc344bea9771f0119ce5f4dConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(localdb)\\MSSQLLocalDB;Initial Catalog=PAQUETERIAMK_ea2898f283f84a938" +
            "8da3c9c3847e7fb;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustS" +
            "erverCertificate=True")]
        public string PAQUETERIAMK_ea2898f283f84a9388da3c9c3847e7fbConnectionString {
            get {
                return ((string)(this["PAQUETERIAMK_ea2898f283f84a9388da3c9c3847e7fbConnectionString"]));
            }
        }
    }
}
